### ISSUE TITLE
`childrenOfType`?

### ISSUE THREAD

**Issue by ryan-sandy** [facebook/prop-types#209] opened 2018-08-21 18:31 UTC
How would people feel about a children shorthand?

```
const children = PropTypes.oneOfType([
  PropTypes.arrayOf(PropTypes.node),
  PropTypes.node
])
```

**Comment by ljharb** [comment] 2018-08-21 18:35
airbnb-prop-types has childrenOf, which is a bit more useful than just “node” imo.

**Comment by ryan-sandy** [comment] 2018-08-21 18:38
@ljharb That's a nifty package. I didn't know it existed. Thanks for the tip. I think this will solve my problems.

**Comment by oleblaesing** [comment] 2018-09-19 15:12
Is something like `childrenOfType` also planned for `prop-types`? It's quite useful, to guarantee the correct use of compound components. 😄

**Comment by ljharb** [comment] 2019-02-21 22:32
Closing as a duplicate of #61.

**Closed by ljharb** 2019-02-21 22:32 UTC
Labels: new validator request
