### ISSUE TITLE
Feature Request: inspectable type objects

### ISSUE THREAD

**Issue by mgummelt** [facebook/prop-types#145] opened 2017-12-05 19:05 UTC
Currently, AFAICT, given:

```
const type = PropTypes.instanceOf(Customer)
```

there is no way to determine the JS type that `type` represents.  I'd like to use this information to conditionally render fields in an HTML form.

It would be helpful if the objects, which are currently functions, returned by `PropTypes` include properties that specify what type they represent.  Currently this information is stored in a closure, rather than in object attributes, which has the unfortunate property that client code can't access it.

Thanks!

**Comment by icd2k3** [comment] 2017-12-07 16:28
I would love something like this as well. I'm currently working on an automatic jest component snapshot method that would take a component's propTypes and render fixtures for them _based_ on the type of the prop. So far I've had a lot of trouble determining what type it is. Ex: `MyComponent.propTypes.propName` - what would be the best way to find what that type is?

**Comment by ljharb** [comment] 2019-02-21 21:44
Duplicate of #60.

**Closed by ljharb** 2019-02-21 21:44 UTC
