### ISSUE TITLE
Ability to reflect on prop-type instances?

### ISSUE THREAD

**Issue by awfulaxolotl** [facebook/prop-types#161] opened 2018-02-21 08:40 UTC
Hello!

I'm looking for a way to reflect on generated prop-type instances. The purpose is for use in developer tooling.

The problem is that the generated instances are opaque functions with any meaningful metadata hidden in closures. I could maybe see this by design to discourage monkey-patching, but it's closing the door on some cool possibilities.

**Example:** https://runkit.com/awfulaxolotl/lack-of-reflection-in-prop-types
**A use case:** https://github.com/awfulaxolotl/tastes/issues/6

So I guess my question comes down to:

1. **Could this be an addition?**
2. **If I made a PR, would it be accepted?**

Thanks!

**Comment by wjljack** [comment] 2018-03-14 05:35
i need too,use in storybook knobs,reflect prop-types can auto generate knobs easily.

**Comment by cpimhoff** [comment] 2018-05-11 18:45
Given a proptype value specified on an object, you can find the key it comes from via a brute force search. This only works for the basic prop types (ie. not things like `arrayOf`), and not in production, since all the functions of the `prop-type` package is shimmed out when the `nodeEnv` is _production_.


```js
import PropTypes from 'prop-types';
import findKey from 'lodash/findKey';

MyButton.propTypes = {
    disabled: PropTypes.bool
    onClick: PropTypes.func.isRequired
};

function getPropTypeName(typeEntry) {
    return findKey(PropTypes, p => p === typeEntry || p.isRequired === typeEntry);
}

getPropTypeName(MyButton.propTypes.disabled);  // 'bool'
getPropTypeName(MyButton.propTypes.disabled);  // 'func'
```

**Comment by ljharb** [comment] 2018-05-11 18:48
https://npmjs.com/find-value-locations can help with that

**Comment by awfulaxolotl** [comment] 2018-05-12 16:11
@cpimhoff @ljharb Thanks for the help on a partial solution. Looking up prop types by reference is certainly better than nothing :smile_cat: 

However, full reflection is unfortunately required for my usecases. This includes reflecting on nested prop types and other prop types with custom constructor arguments.

**Comment by ljharb** [comment] 2019-02-21 21:45
Duplicate of #60.

**Closed by ljharb** 2019-02-21 21:45 UTC
