### ISSUE TITLE
Check if prop is a given <Component/>

### ISSUE THREAD

**Issue by plysik** [facebook/prop-types#257] opened 2019-02-13 12:01 UTC
Hello, 

how can I make the children prop to accept only specified Component?

```javascript
<Parent>
    <Input/>
</Parent>
```

I want to Parent to accept only Input element (not any element ) as its child.

**Comment by ljharb** [comment] 2019-02-13 17:35
prop-types doesn’t have this built in; you may want childrenOf from https://npmjs.com/airbnb-prop-types

**Comment by ljharb** [comment] 2019-02-21 22:03
Duplicate of #209.

**Closed by ljharb** 2019-02-21 22:03 UTC
Labels: new validator request, question
