### ISSUE TITLE
Unmet dependency for react 15.2.*

### ISSUE THREAD

**Issue by echorohit** [facebook/prop-types#49] opened 2017-05-12 07:19 UTC
+-- prop-types@15.5.9
+-- UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0
`-- UNMET PEER DEPENDENCY react-dom@^15.4.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-addons-perf@15.4.2 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN react-perf-tool@0.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN ET@0.0.1 No repository field.
npm WARN ET@0.0.1 No license field.

**Comment by ljharb** [comment] 2019-02-11 07:11
I'm not clear on what the issue is here; closing.

**Closed by ljharb** 2019-02-11 07:11 UTC
