### ISSUE TITLE
Proptypes validation of shape inside an array

### ISSUE THREAD

**Issue by oswagner** [facebook/prop-types#181] opened 2018-04-26 22:51 UTC
We have an array of objects and when try to validade the shape of the object inside that array, it seems to ignore that validation.

```
data: PropTypes.arrayOf(PropTypes.shape({
 someValue: PropTypes.bool
})
```

if we change **PropTypes.bool** in the sample above for **PropTypes.potato**, like below:

```
data: PropTypes.arrayOf(PropTypes.shape({
 someValue: PropTypes.potato
})
```

We don't receive any kind of message about the error.

**Comment by oswagner** [comment] 2018-04-27 22:38
@ljharb Sorry, but when I gave the example of **PropTypes.potato**. It refers if I try to change to any other type, the same problem occurs, even if I use something like ``PropTypes.number`` 😆

**Comment by ljharb** [comment] 2018-04-27 23:37
@oswagner see https://jsfiddle.net/69z2wepo/182882/ - I see a propType warning in the console, and when I change "number" to "string", it no longer shows an error.

Are you sure you're using the development build of React? The production build of react doesn't check propTypes.

**Comment by ljharb** [comment] 2019-02-21 22:11
This might be caused by #220; closing as both a duplicate and answered.

**Closed by ljharb** 2019-02-21 22:11 UTC
