### ISSUE TITLE
Allow a way to suppress warnings.

### ISSUE THREAD

**Issue by MartinDawson** [facebook/prop-types#135] opened 2017-11-09 00:30 UTC
I supply a third party package via npm and the components I am providing requires that the user provide children prop types.

99% of the time this is correct but 1% of the time this prop type isn't required?

I feel like the best solution to this is to keep the children as a required prop for my component but give the user using my components the ability to suppress this warning.

I see 3 options:

- Allow the user to suppress prop type warning for the 1% use case.
- Tell the user to give a dummy child to satisfy the prop type
- Make my component children a non-required prop, but this obviously isn't great for the other 99% of other people.

What does anyone else think?

**Comment by ljharb** [comment] 2017-11-09 00:41
In what circumstances is it not required?

**Comment by jeffvandyke** [comment] 2017-11-10 19:47
IIRC, prop-types allows a custom validator function to be defined. Can you use that to detect your 1% use case?

**Comment by ljharb** [comment] 2019-02-21 22:43
A custom validator may be the solution here; either way, closing as a duplicate of #192.

**Closed by ljharb** 2019-02-21 22:43 UTC
