### ISSUE TITLE
Give developers the ability to create ".isRequired"-style type checker

### ISSUE THREAD

**Issue by chengjianhua** [facebook/prop-types#170] opened 2018-03-14 17:27 UTC
Feature Request:

All the type checkers of `PropTypes` are created by `createChainableTypeChecker ` to create type checker with the chainable property `isRequired`.

Developers are also want to create the custom type checker keeps the same style of native type checkers provided by `PropTypes` and without the effort to repeat the work that `prop-types` have done. Okay, I know that we could do this ourselves, but if this will be provided, things are more easier and consistent.

So, It's feasible to export the `createChainbleTypeChecker` to developers ? BTW, may a shorter name.

**Comment by metalsheep** [comment] 2018-04-04 23:33
Agreed though I would suggest exporting a function named required() and just replacing the .isRequired syntax with required() going forward.  Leave the other for compatibility, but
```
import { required, string } from 'prop-types';
const propTypes = { name: required(string), somethingCrazy: requried(somethingCrazy) }
```
is a lot more idiomatic IMO.

**Comment by ljharb** [comment] 2019-02-21 22:42
Duplicate of #149.

**Closed by ljharb** 2019-02-21 22:42 UTC
