### ISSUE TITLE
Invalid isRequired could likely use a better error message

### ISSUE THREAD

**Issue by et** [facebook/prop-types#141] opened 2017-11-27 18:49 UTC
I have this as my code:

```js
LoanForm.propTypes = {
  handleSubmit: PropTypes.func.isRequired,
  loan: PropTypes.object.isRequred
};
```

and received the following error message:

`Failed prop type: LoanFormInner: prop type 'loan' is invalid; it must be a function, usually from the 'prop-type'  package, but received 'undefined'.`

The subtlety is that in `loan: PropTypes.object.isRequred`, `isRequired` is spelled wrong. It didn't take me too long to discover the spelling error but the error message didn't really help. 

I am curious if you all would be opened to making the error message a little more clear.

**Comment by ljharb** [comment] 2019-02-21 21:43
I think this is a duplicate of #118. Also a duplicate of #101.

**Closed by ljharb** 2019-02-21 21:43 UTC
